Demo: Pointers to class member functions

row: 1	col: 1	rm: 8
row: 1	col: 2	rm: 7
row: 1	col: 3	rm: 6
row: 2	col: 1	rm: 5
row: 2	col: 2	rm: 4
row: 2	col: 3	rm: 3
row: 3	col: 1	rm: 2
row: 3	col: 2	rm: 1
row: 3	col: 3	rm: 0
row: 1	col: 1	rm: 8


row: 3	col: 3	rm: 0
row: 3	col: 2	rm: 1
row: 3	col: 1	rm: 2
row: 2	col: 3	rm: 3
row: 2	col: 2	rm: 4
row: 2	col: 1	rm: 5
row: 1	col: 3	rm: 6
row: 1	col: 2	rm: 7
row: 1	col: 1	rm: 8
row: 3	col: 3	rm: 0


row: 1	col: 1	rm: 8
row: 1	col: 2	rm: 7
row: 1	col: 3	rm: 6
row: 2	col: 1	rm: 5
row: 2	col: 2	rm: 4
row: 2	col: 3	rm: 3
row: 3	col: 1	rm: 2
row: 3	col: 2	rm: 1
row: 3	col: 3	rm: 0
row: 1	col: 1	rm: 8
