A Program to Illustrate Virtual Functions
ZooAnimal name: Giant Panda
	scientific name:	Ailuropoda Melaoleuca
	we call our friend:	Yin Yang
	Zoo Area Location:
	NorthWest: B1.P: area BrownSpots
	Room Location:	1001

ZooAnimal name: Red Panda
	scientific name:	Ailurus fulgens
	we call our friend:	Rocky
	Zoo Area Location:
	NorthWest: B1.P: area BrownSpots
	Room Location:	943

ZooAnimal name: cartoon Bear
	scientific name:	ursus cartoonus
	Zoo Area Location:
	NorthWest: B1: area Brown

ZooAnimal name: circusZooAnimal

