Invocation by a ZooAnimal object:
ZooAnimal name: circusZooAnimal


Invocation by a Bear object:
ZooAnimal name: cartoon Bear
	scientific name:	ursus cartoonus
	Zoo Area Location:
	NorthWest: B1: area Brown


Invocation by a Panda object:
ZooAnimal name: Giant Panda
	scientific name:	Ailuropoda Melaoleuca
	we call our friend:	Yin Yang
	Zoo Area Location:
	NorthWest: B1.P: area BrownSpots
	Room Location:	1001

