.\" ident	@(#)local:man/intro.3	3.2
.\"
.\" C++ Standard Components, Release 3.0.
.\"
.\" Copyright (c) 1991, 1992 AT&T and UNIX System Laboratories, Inc.
.\" Copyright (c) 1988, 1989, 1990 AT&T.  All Rights Reserved.
.\"
.\" THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T and UNIX System
.\" Laboratories, Inc.  The copyright notice above does not evidence
.\" any actual or intended publication of such source code.
.\" 
.TH \f3intro\fP \f33C++\fP  " "
.SH NAME
intro \- introduction to Section 3C++
.SH DESCRIPTION
This section describes the following components:
.SS "\f3Args(3C++)\fP"
UNIX command line arguments
.SS "\f3Array_alg(3C++)\fP"
Operations on contiguously stored data
.SS "\f3Bits(3C++)\fP"
Variable-length bit strings
.SS "\f3Block(3C++)\fP"
Parameterized variable-size arrays
.SS "\f3Fsm(3C++)\fP"
Simple deterministic finite state machines
.SS "\f3G2++(3C++)\fP"
Runtime support for G2++ data language
.SS "\f3Graph(3C++)\fP"
Graph, Vertex, and Edge - entities and relationships
.SS "\f3Graph_alg(3C++)\fP"
Operations on Graphs
.SS "\f3List(3C++)\fP"
Parameterized variable-length sequences
.SS "\f3Map(3C++)\fP"
Parameterized variable-size associative arrays
.SS "\f3Objection(3C++)\fP"
Unified error-handling 
(used by other components to report errors)
.SS "\f3Path(3C++)\fP"
UNIX pathnames and search paths
.SS "\f3Pool(3C++)\fP"
Special-purpose memory allocators
.SS "\f3Regex(3C++)\fP"
Regular expression processor
.SS "\f3Set(3C++)\fP"
Parameterized unordered collections 
.SS "\f3Stopwatch(3C++)\fP"
Program execution time measurement
.SS "\f3String(3C++)\fP"
Variable-length character strings
.SS "\f3Strstream(3C++)\fP"
\f3iostream(3C++)\f1 specialized to \f3Strings(.)\f1
.SS "\f3Symbol(3C++)\fP"
Unique identifiers based on character strings
.SS "\f3Time(3C++)\fP"
Calendar date and time-of-day relative to particular places
