flight 1 arriving for landing
flight 1 landing 
flight 2 arriving for landing
flight 2 landing 
flight 3 arriving for landing
flight 3 landing 
flight 1 leaving gate
flight 1 taking off
flight 1 arriving for landing
flight 2 leaving gate
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 2 landing 
flight 4 arriving for landing
flight 4 landing 
flight 3 leaving gate
flight 3 taking off
flight 3 arriving for landing
flight 1 leaving gate
flight 3 landing 
flight 1 taking off
flight 1 arriving for landing
flight 2 leaving gate
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 2 landing 
flight 5 arriving for landing
flight 4 leaving gate
flight 5 landing 
flight 4 taking off
flight 4 arriving for landing
flight 4 landing 
flight 3 leaving gate
flight 3 taking off
flight 3 arriving for landing
flight 3 landing 
flight 6 arriving for landing
flight 1 leaving gate
flight 6 landing 
flight 1 taking off
flight 1 arriving for landing
flight 2 leaving gate
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 2 landing 
flight 5 leaving gate
flight 5 taking off
flight 5 arriving for landing
flight 4 leaving gate
flight 5 landing 
flight 4 taking off
flight 3 leaving gate
flight 3 taking off
flight 4 arriving for landing
flight 6 leaving gate
flight 4 landing 
flight 6 taking off
flight 3 arriving for landing
flight 1 leaving gate
flight 3 landing 
flight 1 taking off
flight 6 arriving for landing
flight 6 landing 
flight 2 leaving gate
flight 1 arriving for landing
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 2 landing 
flight 7 arriving for landing
flight 5 leaving gate
flight 7 landing 
flight 5 taking off
flight 5 arriving for landing
flight 4 leaving gate
flight 5 landing 
flight 4 taking off
flight 4 arriving for landing
flight 3 leaving gate
flight 4 landing 
flight 3 taking off
flight 6 leaving gate
flight 6 taking off
flight 3 arriving for landing
flight 3 landing 
flight 6 arriving for landing
flight 6 landing 
flight 1 leaving gate
flight 8 arriving for landing
flight 8 landing 
flight 1 taking off
flight 2 leaving gate
flight 2 taking off
flight 1 arriving for landing
flight 1 landing 
flight 7 leaving gate
flight 7 taking off
flight 2 arriving for landing
flight 2 landing 
flight 7 arriving for landing
flight 9 arriving for landing
flight 7 landing 
flight 5 leaving gate
flight 9 landing 
flight 5 taking off
flight 5 arriving for landing
flight 5 landing 
flight 10 arriving for landing
flight 10 landing 
flight 4 leaving gate
flight 11 arriving for landing
flight 11 landing 
flight 4 taking off
flight 4 arriving for landing
flight 3 leaving gate
flight 4 landing 
flight 3 taking off
flight 3 arriving for landing
flight 6 leaving gate
flight 3 landing 
flight 6 taking off
flight 6 arriving for landing
flight 6 landing 
flight 8 leaving gate
flight 8 taking off
flight 8 arriving for landing
flight 12 arriving for landing
flight 8 landing 
flight 12 landing 
flight 1 leaving gate
flight 13 arriving for landing
flight 13 landing 
flight 1 taking off
flight 2 leaving gate
flight 2 taking off
flight 1 arriving for landing
flight 7 leaving gate
flight 1 landing 
flight 7 taking off
flight 2 arriving for landing
flight 2 landing 
flight 9 leaving gate
flight 9 taking off
flight 5 leaving gate
flight 7 arriving for landing
flight 7 landing 
flight 5 taking off
flight 10 leaving gate
flight 9 arriving for landing
flight 9 landing 
flight 10 taking off
flight 11 leaving gate
flight 11 taking off
flight 5 arriving for landing
flight 5 landing 
flight 4 leaving gate
flight 4 taking off
flight 10 arriving for landing
flight 11 arriving for landing
flight 10 landing 
flight 3 leaving gate
flight 11 landing 
flight 3 taking off
flight 4 arriving for landing
flight 4 landing 
flight 6 leaving gate
flight 6 taking off
flight 3 arriving for landing
flight 8 leaving gate
flight 3 landing 
flight 8 taking off
flight 6 arriving for landing
flight 12 leaving gate
flight 6 landing 
flight 12 taking off
flight 8 arriving for landing
flight 8 landing 
flight 13 leaving gate
flight 13 taking off
flight 12 arriving for landing
flight 1 leaving gate
flight 12 landing 
flight 1 taking off
flight 13 arriving for landing
flight 13 landing 
flight 2 leaving gate
flight 2 taking off
flight 1 arriving for landing
flight 2 arriving for landing
flight 1 landing 
flight 14 arriving for landing
flight 2 landing 
flight 15 arriving for landing
flight 7 leaving gate
flight 14 landing 
flight 7 taking off
flight 7 arriving for landing
flight 15 landing 
flight 9 leaving gate
flight 16 arriving for landing
flight 7 landing 
flight 9 taking off
flight 9 arriving for landing
flight 16 landing 
flight 5 leaving gate
flight 9 landing 
flight 5 taking off
flight 5 arriving for landing
flight 10 leaving gate
flight 5 landing 
flight 10 taking off
flight 10 arriving for landing
flight 17 arriving for landing
flight 18 arriving for landing
flight 10 landing 
flight 11 leaving gate
flight 17 landing 
flight 11 taking off
flight 18 landing 
flight 11 arriving for landing
flight 4 leaving gate
flight 11 landing 
flight 4 taking off
flight 4 arriving for landing
flight 4 landing 
flight 3 leaving gate
flight 19 arriving for landing
flight 19 landing 
flight 3 taking off
flight 3 arriving for landing
flight 3 landing 
flight 20 arriving for landing
flight 20 landing 
flight 6 leaving gate
flight 21 arriving for landing
flight 21 landing 
flight 6 taking off
flight 6 arriving for landing
flight 8 leaving gate
flight 6 landing 
flight 8 taking off
flight 8 arriving for landing
flight 22 arriving for landing
flight 8 landing 
flight 22 landing 
flight 12 leaving gate
flight 12 taking off
flight 12 arriving for landing
flight 12 landing 
flight 13 leaving gate
flight 13 taking off
flight 1 leaving gate
flight 13 arriving for landing
flight 13 landing 
flight 1 taking off
flight 2 leaving gate
flight 1 arriving for landing
flight 1 landing 
flight 2 taking off
flight 14 leaving gate
flight 2 arriving for landing
flight 2 landing 
flight 14 taking off
flight 14 arriving for landing
flight 14 landing 
flight 15 leaving gate
flight 15 taking off
flight 15 arriving for landing
flight 15 landing 
flight 7 leaving gate
flight 23 arriving for landing
flight 23 landing 
flight 7 taking off
flight 16 leaving gate
flight 7 arriving for landing
flight 7 landing 
flight 16 taking off
flight 16 arriving for landing
flight 16 landing 
flight 9 leaving gate
flight 9 taking off
flight 5 leaving gate
flight 9 arriving for landing
flight 9 landing 
flight 5 taking off
flight 10 leaving gate
flight 10 taking off
flight 17 leaving gate
flight 17 taking off
flight 5 arriving for landing
flight 10 arriving for landing
flight 5 landing 
flight 10 landing 
flight 18 leaving gate
flight 17 arriving for landing
flight 17 landing 
flight 18 taking off
flight 18 arriving for landing
flight 18 landing 
flight 11 leaving gate
flight 11 taking off
flight 11 arriving for landing
flight 4 leaving gate
flight 24 arriving for landing
flight 25 arriving for landing
flight 11 landing 
flight 4 taking off
flight 19 leaving gate
flight 24 landing 
flight 19 taking off
flight 3 leaving gate
flight 25 landing 
flight 3 taking off
flight 4 arriving for landing
flight 4 landing 
flight 20 leaving gate
flight 20 taking off
flight 19 arriving for landing
flight 3 arriving for landing
flight 19 landing 
flight 21 leaving gate
flight 20 arriving for landing
flight 3 landing 
flight 21 taking off
flight 20 landing 
flight 6 leaving gate
flight 21 arriving for landing
flight 21 landing 
flight 6 taking off
flight 6 arriving for landing
flight 8 leaving gate
flight 6 landing 
flight 8 taking off
flight 8 arriving for landing
flight 8 landing 
flight 22 leaving gate
flight 26 arriving for landing
flight 26 landing 
flight 22 taking off
flight 12 leaving gate
flight 12 taking off
flight 22 arriving for landing
flight 22 landing 
flight 13 leaving gate
flight 13 taking off
flight 12 arriving for landing
flight 13 arriving for landing
flight 12 landing 
flight 1 leaving gate
flight 13 landing 
flight 1 taking off
flight 2 leaving gate
flight 1 arriving for landing
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 2 landing 
flight 27 arriving for landing
flight 14 leaving gate
flight 27 landing 
flight 14 taking off
flight 14 arriving for landing
flight 28 arriving for landing
flight 15 leaving gate
flight 14 landing 
flight 15 taking off
flight 15 arriving for landing
flight 28 landing 
flight 23 leaving gate
flight 29 arriving for landing
flight 15 landing 
flight 23 taking off
flight 23 arriving for landing
flight 29 landing 
flight 7 leaving gate
flight 23 landing 
flight 7 taking off
flight 7 arriving for landing
flight 7 landing 
flight 16 leaving gate
flight 30 arriving for landing
flight 30 landing 
flight 16 taking off
flight 16 arriving for landing
flight 16 landing 
flight 31 arriving for landing
flight 9 leaving gate
flight 31 landing 
flight 9 taking off
flight 5 leaving gate
flight 9 arriving for landing
flight 9 landing 
flight 5 taking off
flight 5 arriving for landing
flight 10 leaving gate
flight 5 landing 
flight 10 taking off
flight 17 leaving gate
flight 17 taking off
flight 10 arriving for landing
flight 10 landing 
flight 17 arriving for landing
flight 17 landing 
flight 32 arriving for landing
flight 18 leaving gate
flight 32 landing 
flight 18 taking off
flight 11 leaving gate
flight 18 arriving for landing
flight 18 landing 
flight 11 taking off
flight 24 leaving gate
flight 24 taking off
flight 11 arriving for landing
flight 11 landing 
flight 25 leaving gate
flight 24 arriving for landing
flight 24 landing 
flight 25 taking off
flight 25 arriving for landing
flight 25 landing 
flight 33 arriving for landing
flight 4 leaving gate
flight 33 landing 
flight 4 taking off
flight 4 arriving for landing
flight 19 leaving gate
flight 4 landing 
flight 19 taking off
flight 19 arriving for landing
flight 3 leaving gate
flight 19 landing 
flight 3 taking off
flight 3 arriving for landing
flight 3 landing 
flight 34 arriving for landing
flight 20 leaving gate
flight 34 landing 
flight 20 taking off
flight 20 arriving for landing
flight 21 leaving gate
flight 20 landing 
flight 21 taking off
flight 21 arriving for landing
flight 21 landing 
flight 6 leaving gate
flight 35 arriving for landing
flight 35 landing 
flight 6 taking off
flight 8 leaving gate
flight 8 taking off
flight 6 arriving for landing
flight 6 landing 
flight 26 leaving gate
flight 8 arriving for landing
flight 8 landing 
flight 26 taking off
flight 26 arriving for landing
flight 22 leaving gate
flight 26 landing 
flight 22 taking off
flight 12 leaving gate
flight 22 arriving for landing
flight 22 landing 
flight 12 taking off
flight 12 arriving for landing
flight 13 leaving gate
flight 12 landing 
flight 13 taking off
flight 1 leaving gate
flight 1 taking off
flight 13 arriving for landing
flight 13 landing 
flight 2 leaving gate
flight 2 taking off
flight 1 arriving for landing
flight 27 leaving gate
flight 1 landing 
flight 27 taking off
flight 2 arriving for landing
flight 14 leaving gate
flight 2 landing 
flight 14 taking off
flight 27 arriving for landing
flight 14 arriving for landing
flight 27 landing 
flight 28 leaving gate
flight 14 landing 
flight 28 taking off
flight 28 arriving for landing
flight 28 landing 
flight 15 leaving gate
flight 36 arriving for landing
flight 36 landing 
flight 15 taking off
flight 15 arriving for landing
flight 29 leaving gate
flight 15 landing 
flight 29 taking off
flight 29 arriving for landing
flight 29 landing 
flight 23 leaving gate
flight 23 taking off
flight 23 arriving for landing
flight 23 landing 
flight 7 leaving gate
flight 7 taking off
flight 30 leaving gate
flight 7 arriving for landing
flight 7 landing 
flight 30 taking off
flight 16 leaving gate
flight 16 taking off
flight 30 arriving for landing
flight 30 landing 
flight 31 leaving gate
flight 31 taking off
flight 16 arriving for landing
flight 9 leaving gate
flight 16 landing 
flight 9 taking off
flight 31 arriving for landing
flight 5 leaving gate
flight 31 landing 
flight 5 taking off
flight 10 leaving gate
flight 10 taking off
flight 9 arriving for landing
flight 17 leaving gate
flight 9 landing 
flight 17 taking off
flight 5 arriving for landing
flight 5 landing 
flight 32 leaving gate
flight 10 arriving for landing
flight 10 landing 
flight 32 taking off
flight 18 leaving gate
flight 18 taking off
flight 17 arriving for landing
flight 32 arriving for landing
flight 18 arriving for landing
flight 17 landing 
flight 11 leaving gate
flight 37 arriving for landing
flight 32 landing 
flight 11 taking off
flight 18 landing 
flight 24 leaving gate
flight 11 arriving for landing
flight 37 landing 
flight 24 taking off
flight 25 leaving gate
flight 11 landing 
flight 25 taking off
flight 24 arriving for landing
flight 24 landing 
flight 25 arriving for landing
flight 33 leaving gate
flight 25 landing 
flight 33 taking off
flight 33 arriving for landing
flight 33 landing 
flight 4 leaving gate
flight 4 taking off
flight 4 arriving for landing
flight 19 leaving gate
flight 4 landing 
flight 19 taking off
flight 19 arriving for landing
flight 3 leaving gate
flight 19 landing 
flight 3 taking off
flight 34 leaving gate
flight 34 taking off
flight 3 arriving for landing
flight 3 landing 
flight 20 leaving gate
flight 20 taking off
flight 34 arriving for landing
flight 34 landing 
flight 21 leaving gate
flight 20 arriving for landing
flight 20 landing 
flight 21 taking off
flight 21 arriving for landing
flight 21 landing 
flight 38 arriving for landing
flight 35 leaving gate
flight 38 landing 
flight 35 taking off
flight 6 leaving gate
flight 35 arriving for landing
flight 35 landing 
flight 6 taking off
flight 8 leaving gate
flight 6 arriving for landing
flight 6 landing 
flight 8 taking off
flight 26 leaving gate
flight 26 taking off
flight 8 arriving for landing
flight 26 arriving for landing
flight 8 landing 
flight 22 leaving gate
flight 26 landing 
flight 22 taking off
flight 22 arriving for landing
flight 22 landing 
flight 12 leaving gate
flight 39 arriving for landing
flight 39 landing 
flight 12 taking off
flight 13 leaving gate
flight 13 taking off
flight 12 arriving for landing
flight 12 landing 
flight 13 arriving for landing
flight 1 leaving gate
flight 13 landing 
flight 1 taking off
flight 1 arriving for landing
flight 2 leaving gate
flight 1 landing 
flight 2 taking off
flight 2 arriving for landing
flight 40 arriving for landing
flight 27 leaving gate
flight 2 landing 
flight 27 taking off
flight 40 landing 
flight 14 leaving gate
flight 27 arriving for landing
flight 27 landing 
flight 14 taking off
flight 28 leaving gate
flight 14 arriving for landing
flight 14 landing 
flight 28 taking off
flight 36 leaving gate
flight 36 taking off
flight 28 arriving for landing
flight 15 leaving gate
flight 36 arriving for landing
flight 28 landing 
flight 15 taking off
flight 15 arriving for landing
flight 41 arriving for landing
flight 42 arriving for landing
flight 36 landing 
flight 15 landing 
flight 29 leaving gate
flight 43 arriving for landing
flight 41 landing 
flight 29 taking off
flight 29 arriving for landing
flight 42 landing 
flight 44 arriving for landing
flight 43 landing 
flight 23 leaving gate
flight 29 landing 
flight 23 taking off
flight 44 landing 
flight 23 arriving for landing
flight 7 leaving gate
flight 23 landing 
flight 7 taking off
flight 7 arriving for landing
flight 45 arriving for landing
flight 46 arriving for landing
flight 7 landing 
flight 45 landing 
flight 30 leaving gate
flight 47 arriving for landing
flight 46 landing 
flight 30 taking off
flight 47 landing 
flight 16 leaving gate
flight 30 arriving for landing
flight 30 landing 
flight 16 taking off
flight 31 leaving gate
flight 16 arriving for landing
flight 16 landing 
flight 31 taking off
flight 31 arriving for landing
flight 9 leaving gate
flight 31 landing 
flight 9 taking off
flight 9 arriving for landing
flight 9 landing 
flight 5 leaving gate
flight 5 taking off
flight 5 arriving for landing
flight 5 landing 
flight 48 arriving for landing
flight 48 landing 
flight 10 leaving gate
flight 10 taking off
flight 10 arriving for landing
flight 17 leaving gate
flight 10 landing 
flight 17 taking off
flight 32 leaving gate
flight 32 taking off
flight 17 arriving for landing
flight 18 leaving gate
flight 17 landing 
flight 18 taking off
flight 32 arriving for landing
flight 32 landing 
flight 37 leaving gate
flight 37 taking off
flight 18 arriving for landing
flight 18 landing 
flight 11 leaving gate
flight 37 arriving for landing
flight 37 landing 
flight 11 taking off
flight 24 leaving gate
flight 24 taking off
flight 11 arriving for landing
flight 11 landing 
flight 25 leaving gate
flight 25 taking off
flight 24 arriving for landing
flight 24 landing 
flight 33 leaving gate
flight 25 arriving for landing
flight 49 arriving for landing
flight 25 landing 
flight 33 taking off
flight 49 landing 
flight 4 leaving gate
flight 4 taking off
flight 33 arriving for landing
flight 33 landing 
flight 19 leaving gate
flight 19 taking off
flight 4 arriving for landing
flight 19 arriving for landing
flight 4 landing 
flight 50 arriving for landing
flight 19 landing 
flight 3 leaving gate
flight 50 landing 
flight 3 taking off
flight 34 leaving gate
flight 3 arriving for landing
flight 3 landing 
flight 34 taking off
flight 20 leaving gate
flight 20 taking off
flight 34 arriving for landing
flight 34 landing 
flight 20 arriving for landing
flight 21 leaving gate
flight 51 arriving for landing
flight 20 landing 
flight 21 taking off
flight 51 landing 
flight 38 leaving gate
flight 21 arriving for landing
flight 52 arriving for landing
flight 21 landing 
flight 38 taking off
flight 38 arriving for landing
flight 52 landing delayed 
flight 35 leaving gate
flight 52 landing 
flight 35 taking off
flight 35 arriving for landing
flight 38 landing delayed 
flight 53 arriving for landing
flight 6 leaving gate
flight 38 landing 
flight 6 taking off
flight 8 leaving gate
flight 35 landing 
flight 8 taking off
flight 6 arriving for landing
flight 53 landing delayed 
flight 53 crash landing!
flight 8 arriving for landing
flight 26 leaving gate
flight 6 landing 
flight 26 taking off
flight 26 arriving for landing
flight 54 arriving for landing
flight 8 landing delayed 
flight 22 leaving gate
flight 8 landing 
flight 22 taking off
flight 22 arriving for landing
flight 26 landing delayed 
flight 55 arriving for landing
flight 26 crash landing!
flight 39 leaving gate
flight 56 arriving for landing
flight 54 landing 
flight 39 taking off
flight 12 leaving gate
flight 22 landing 
flight 12 taking off
flight 39 arriving for landing
flight 55 landing delayed 
flight 12 arriving for landing
flight 55 crash landing!
flight 13 leaving gate
flight 56 landing 
flight 13 taking off
flight 13 arriving for landing
flight 1 leaving gate
flight 39 landing 
flight 1 taking off
flight 2 leaving gate
flight 12 landing 
flight 2 taking off
flight 13 landing delayed 
flight 1 arriving for landing
flight 13 crash landing!
flight 40 leaving gate
flight 1 landing 
flight 40 taking off
flight 2 arriving for landing
flight 40 arriving for landing
flight 2 landing delayed 
flight 27 leaving gate
flight 2 landing 
flight 27 taking off
flight 27 arriving for landing
flight 40 landing delayed 
flight 57 arriving for landing
flight 40 crash landing!
flight 14 leaving gate
flight 58 arriving for landing
flight 27 landing 
flight 14 taking off
flight 28 leaving gate
flight 57 landing 
flight 28 taking off
flight 36 leaving gate
flight 14 arriving for landing
flight 58 landing 
flight 36 taking off
flight 15 leaving gate
flight 14 landing 
flight 15 taking off
flight 41 leaving gate
flight 28 arriving for landing
flight 28 landing 
flight 41 taking off
flight 42 leaving gate
flight 36 arriving for landing
flight 36 landing 
flight 42 taking off
flight 43 leaving gate
flight 43 taking off
flight 15 arriving for landing
flight 15 landing 
flight 29 leaving gate
flight 41 arriving for landing
flight 41 landing 
flight 29 taking off
flight 42 arriving for landing
flight 42 landing delayed 
flight 44 leaving gate
flight 42 landing 
flight 44 taking off
flight 23 leaving gate
flight 23 taking off
flight 43 arriving for landing
flight 7 leaving gate
flight 43 landing 
flight 7 taking off
flight 29 arriving for landing
flight 45 leaving gate
flight 29 landing 
flight 45 taking off
flight 44 arriving for landing
flight 44 landing 
flight 46 leaving gate
flight 46 taking off
flight 23 arriving for landing
flight 23 landing 
flight 47 leaving gate
flight 7 arriving for landing
flight 7 landing 
flight 47 taking off
flight 45 arriving for landing
flight 30 leaving gate
flight 45 landing 
flight 30 taking off
flight 46 arriving for landing
flight 46 landing delayed 
flight 16 leaving gate
flight 46 landing 
flight 16 taking off
flight 47 arriving for landing
flight 47 landing delayed 
flight 31 leaving gate
flight 30 arriving for landing
flight 47 landing 
flight 31 taking off
flight 30 landing delayed 
flight 9 leaving gate
flight 30 landing 
flight 9 taking off
flight 16 arriving for landing
flight 5 leaving gate
flight 16 landing 
flight 5 taking off
flight 31 arriving for landing
flight 31 landing delayed 
flight 31 landing delayed 
flight 48 leaving gate
flight 31 landing 
flight 48 taking off
flight 9 arriving for landing
flight 9 landing delayed 
flight 5 arriving for landing
flight 9 landing delayed 
flight 10 leaving gate
flight 9 landing 
flight 10 taking off
flight 5 landing delayed 
flight 48 arriving for landing
flight 17 leaving gate
flight 10 arriving for landing
flight 5 landing 
flight 17 taking off
flight 48 landing delayed 
flight 32 leaving gate
flight 48 landing 
flight 32 taking off
flight 17 arriving for landing
flight 10 crash landing!
flight 18 leaving gate
flight 32 arriving for landing
flight 59 arriving for landing
flight 17 landing 
flight 18 taking off
flight 18 arriving for landing
flight 32 landing delayed 
flight 60 arriving for landing
flight 37 leaving gate
flight 32 landing 
flight 37 taking off
flight 37 arriving for landing
flight 61 arriving for landing
flight 62 arriving for landing
flight 59 crash landing!
flight 63 arriving for landing
flight 18 crash landing!
flight 11 leaving gate
flight 60 landing 
flight 11 taking off
flight 11 arriving for landing
flight 64 arriving for landing
flight 24 leaving gate
flight 37 landing 
flight 24 taking off
flight 24 arriving for landing
flight 25 leaving gate
flight 61 landing 
flight 25 taking off
flight 25 arriving for landing
flight 62 crash landing!
flight 63 crash landing!
flight 49 leaving gate
flight 65 arriving for landing
flight 11 landing 
flight 49 taking off
flight 49 arriving for landing
flight 64 crash landing!
flight 66 arriving for landing
flight 24 crash landing!
flight 67 arriving for landing
flight 33 leaving gate
flight 25 landing 
flight 33 taking off
flight 4 leaving gate
flight 65 landing 
flight 4 taking off
flight 33 arriving for landing
flight 4 arriving for landing
flight 49 crash landing!
flight 19 leaving gate
flight 66 landing 
flight 19 taking off
flight 19 arriving for landing
flight 67 crash landing!
flight 50 leaving gate
flight 33 landing 
flight 50 taking off
flight 50 arriving for landing
flight 4 crash landing!
flight 3 leaving gate
flight 68 arriving for landing
flight 19 landing 
flight 3 taking off
flight 50 landing delayed 
flight 3 arriving for landing
flight 69 arriving for landing
flight 34 leaving gate
flight 50 landing 
flight 34 taking off
flight 34 arriving for landing
flight 68 landing delayed 
flight 20 leaving gate
flight 68 landing 
flight 20 taking off
flight 20 arriving for landing
flight 3 crash landing!
flight 70 arriving for landing
flight 51 leaving gate
flight 69 landing 
flight 51 taking off
flight 34 crash landing!
flight 21 leaving gate
flight 20 landing 
flight 21 taking off
flight 51 arriving for landing
flight 52 leaving gate
flight 21 arriving for landing
flight 70 landing 
flight 52 taking off
flight 51 landing delayed 
flight 38 leaving gate
flight 51 landing 
flight 38 taking off
flight 52 arriving for landing
flight 21 crash landing!
flight 38 arriving for landing
flight 35 leaving gate
flight 52 landing 
flight 35 taking off
flight 35 arriving for landing
flight 38 landing delayed 
flight 6 leaving gate
flight 38 landing 
flight 6 taking off
flight 6 arriving for landing
flight 35 landing delayed 
flight 71 arriving for landing
flight 8 leaving gate
flight 35 landing 
flight 8 taking off
flight 6 landing delayed 
flight 8 arriving for landing
flight 54 leaving gate
flight 6 landing 
flight 54 taking off
flight 22 leaving gate
flight 71 landing 
flight 22 taking off
flight 54 arriving for landing
flight 8 landing delayed 
flight 22 arriving for landing
flight 72 arriving for landing
flight 56 leaving gate
flight 8 landing 
flight 56 taking off
flight 54 landing delayed 
flight 39 leaving gate
flight 54 landing 
flight 39 taking off
flight 56 arriving for landing
flight 22 crash landing!
flight 12 leaving gate
flight 72 landing 
flight 12 taking off
flight 39 arriving for landing
flight 56 landing delayed 
flight 1 leaving gate
flight 12 arriving for landing
flight 56 landing 
flight 1 taking off
flight 2 leaving gate
flight 39 landing 
flight 2 taking off
flight 12 landing delayed 
flight 1 arriving for landing
flight 12 crash landing!
flight 27 leaving gate
flight 2 arriving for landing
flight 73 arriving for landing
flight 1 landing 
flight 27 taking off
flight 2 landing delayed 
flight 2 landing delayed 
flight 57 leaving gate
flight 27 arriving for landing
flight 74 arriving for landing
flight 2 landing 
flight 57 taking off
flight 73 crash landing!
flight 58 leaving gate
flight 57 arriving for landing
flight 27 landing 
flight 58 taking off
flight 58 arriving for landing
flight 14 leaving gate
flight 75 arriving for landing
flight 74 landing 
flight 14 taking off
flight 14 arriving for landing
flight 57 landing delayed 
flight 28 leaving gate
flight 57 landing 
flight 28 taking off
flight 58 crash landing!
flight 28 arriving for landing
flight 36 leaving gate
flight 76 arriving for landing
flight 75 landing 
flight 36 taking off
flight 15 leaving gate
flight 14 landing 
flight 15 taking off
flight 36 arriving for landing
flight 28 landing delayed 
flight 28 crash landing!
flight 41 leaving gate
flight 76 landing 
flight 41 taking off
flight 15 arriving for landing
flight 36 crash landing!
flight 15 landing delayed 
flight 42 leaving gate
flight 41 arriving for landing
flight 15 landing 
flight 42 taking off
flight 42 arriving for landing
flight 41 landing delayed 
flight 43 leaving gate
flight 41 landing 
flight 43 taking off
flight 43 arriving for landing
flight 42 landing delayed 
flight 29 leaving gate
flight 42 landing 
flight 29 taking off
flight 43 landing delayed 
flight 29 arriving for landing
flight 44 leaving gate
flight 43 landing 
flight 44 taking off
flight 29 landing delayed 
flight 23 leaving gate
flight 29 landing 
flight 23 taking off
flight 44 arriving for landing
flight 44 landing delayed 
flight 23 arriving for landing
flight 44 landing delayed 
flight 77 arriving for landing
flight 7 leaving gate
flight 78 arriving for landing
flight 44 landing 
flight 7 taking off
flight 7 arriving for landing
flight 23 landing delayed 
flight 45 leaving gate
flight 79 arriving for landing
flight 23 landing 
flight 45 taking off
flight 77 crash landing!
flight 46 leaving gate
flight 45 arriving for landing
flight 78 landing 
flight 46 taking off
flight 7 crash landing!
flight 46 arriving for landing
flight 47 leaving gate
flight 79 landing 
flight 47 taking off
flight 45 crash landing!
flight 47 arriving for landing
flight 46 landing delayed 
flight 30 leaving gate
flight 46 landing 
flight 30 taking off
flight 30 arriving for landing
flight 47 landing delayed 
flight 80 arriving for landing
flight 16 leaving gate
flight 81 arriving for landing
flight 47 landing 
flight 16 taking off
flight 31 leaving gate
flight 30 landing 
flight 31 taking off
flight 16 arriving for landing
flight 80 landing delayed 
flight 31 arriving for landing
flight 80 crash landing!
flight 82 arriving for landing
flight 9 leaving gate
flight 81 landing 
flight 9 taking off
flight 9 arriving for landing
flight 16 crash landing!
flight 5 leaving gate
flight 83 arriving for landing
flight 31 landing 
flight 5 taking off
flight 5 arriving for landing
flight 82 crash landing!
flight 84 arriving for landing
flight 9 landing delayed 
flight 48 leaving gate
flight 9 landing 
flight 48 taking off
flight 48 arriving for landing
flight 17 leaving gate
flight 83 landing 
flight 17 taking off
flight 17 arriving for landing
flight 5 crash landing!
flight 84 crash landing!
flight 32 leaving gate
flight 48 landing 
flight 32 taking off
flight 17 crash landing!
flight 60 leaving gate
Airport Closed
