main
new pc(a,DEDICATED)
new pc(b,SHARED)
new pc(c,DEDICATED)
new pc(d,SHARED)
new pc(e,DEDICATED)
new pc(f,SHARED)
new pc(g,DEDICATED)
new pc(h,SHARED)
new pc(i,DEDICATED)
new pc(j,SHARED)
new pc(k,DEDICATED)
new pc(l,SHARED)
new pc(m,DEDICATED)
new pc(n,SHARED)
new pc(o,DEDICATED)
new pc(p,SHARED)
new pc(q,DEDICATED)
new pc(r,SHARED)
new pc(s,DEDICATED)
new pc(t,SHARED)
new pc(u,DEDICATED)
new pc(v,SHARED)
new pc(w,DEDICATED)
new pc(x,SHARED)
new pc(y,DEDICATED)
new pc(z,SHARED)
z: here we go
main()'s loop
main task: done.
task a: done.
task b: done.
task c: done.
task d: done.
task e: done.
task f: done.
task g: done.
task h: done.
task i: done.
task j: done.
task k: done.
task l: done.
task m: done.
task n: done.
task o: done.
task p: done.
task q: done.
task r: done.
task s: done.
task t: done.
task u: done.
task v: done.
task w: done.
task x: done.
task y: done.
task z: done.
