Server::Server:
Server::Server:  got Message
r_operation:	PLUS
r_arg1:		1
r_arg2:		1
r_reply: HEX
Server::Server:  about to put Message
r_operation:	VALUE
r_arg1:		2
r_arg2:		1
r_reply: HEX
Server::Server:
Server::plus:  got message:
r_operation:	VALUE
r_arg1:		2
r_arg2:		1
r_reply: HEX
main:  two = 2
Server::Server:  got Message
r_operation:	MINUS
r_arg1:		12
r_arg2:		2
r_reply: HEX
Server::Server:  about to put Message
r_operation:	VALUE
r_arg1:		10
r_arg2:		2
r_reply: HEX
Server::Server:
Server::minus:  got message:
r_operation:	VALUE
r_arg1:		10
r_arg2:		2
r_reply: HEX
main:  ten = 10
