Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
main:  all done.
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_task sigusr1 task:  all done.
Sig_sender sigusr1 sender:  all done.
