main
new pc(a)
main()'s loop
new pc(first pc)
main: here we go
main: exit
task a
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task first pc
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task a
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task first pc
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task a
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task first pc
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task a
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task first pc
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task a
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task a: done.
task first pc
got p->randn = HEX  p->randf = 0 HEX
changed values: p->randn = HEX  p->randf = 0 HEX
task first pc: done.
