main
new pc(a)
main()'s loop
new pc(first pc)
main: here we go
main: exit
task a
got p->randn = 0
changed values: p->randn = 11
task first pc
got p->randn = 11
changed values: p->randn = 4
task a
got p->randn = 4
changed values: p->randn = 11
task first pc
got p->randn = 11
changed values: p->randn = 1
task a
got p->randn = 1
changed values: p->randn = 7
task first pc
got p->randn = 7
changed values: p->randn = 7
task a
got p->randn = 7
changed values: p->randn = 9
task first pc
got p->randn = 9
changed values: p->randn = 5
task a
got p->randn = 5
changed values: p->randn = 3
task a: done.
task first pc
got p->randn = 3
changed values: p->randn = 5
task first pc: done.
