.\" ident	@(#)local:man/intro.1	3.3
.\"
.\" C++ Standard Components, Release 3.0.
.\"
.\" Copyright (c) 1991, 1992 AT&T and UNIX System Laboratories, Inc.
.\" Copyright (c) 1988, 1989, 1990 AT&T.  All Rights Reserved.
.\"
.\" THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T and UNIX System
.\" Laboratories, Inc.  The copyright notice above does not evidence
.\" any actual or intended publication of such source code.
.\" 
.TH \f3intro\f1 \f31C++\f1 " "
.SH NAME
intro \- introduction to C++ tools and commands
.SH DESCRIPTION
.LP
This section describes the C++ translator and tools 
in the \fIC++ Standard Components\fP.
The list of commands appears below.
Notice that the exit status for these commands follow the same convention
as for other Section 1 commands, i.e., zero for success and non-zero for error.
.SH "LIST OF COMMANDS"
.sp
.if t .ta 22n; +22n
.if n .ta 18n; +20n
.nf
\fBName	Appears on Page	Description\fR
.sp
\f3CC\f1	\f3CC(1C++)\f1		AT&T C++ translator (cfront)
\f3fscpp\f1	\f3fscpp(1C++)		/lib/cpp\f1 replacement for C++ libraries
\f3c++filt\f1	\f3demangle(1C++)\f1	demangle C++ names in standard input
\f3dem\f1	\f3demangle(1C++)\f1	demangle C++ names in argument list
\f3demangle\f1	\f3demangle(1C++)\f1	demangle C++ names in a.out
\f3g2++comp\f1	\f3g2++comp(1C++)\f1	G2++ compiler
\f3hier\f1	\f3hier(1C++)\f1		draw C++ inheritance hierarchy
\f3incl.sh\f1	\f3incl(1C++)\f1		draw file inclusion hierarchy
\f3publik\f1	\f3publik(1C++)\f1		find and print public parts of C++ class definitions
.fi
