.\" ident	@(#)local:man/intro.4	3.1
.\"
.\" C++ Standard Components, Release 3.0.
.\"
.\" Copyright (c) 1991, 1992 AT&T and UNIX System Laboratories, Inc.
.\" Copyright (c) 1988, 1989, 1990 AT&T.  All Rights Reserved.
.\"
.\" THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T and UNIX System
.\" Laboratories, Inc.  The copyright notice above does not evidence
.\" any actual or intended publication of such source code.
.\" 
.TH \f3intro\f1 \f34C++\f1 " "
.SH NAME
intro \- introduction to C++ tools and library file formats
.SH DESCRIPTION
.LP
This section describes the file formats for C++ tools and
libraries. 
