#!/bin/sh
#ident	"@(#)local:lib/domake	3.1" 
###############################################################################
#
# C++ Standard Components, Release 3.0.
#
# Copyright (c) 1991, 1992 AT&T and Unix System Laboratories, Inc.
# Copyright (c) 1988, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T and Unix System
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
###############################################################################

# This script is only called by the top-level SC makefile.

chmod +x ./aux/*

root=`pwd`
PATH=$root/aux:`pwd`/bin:$PATH
SLELIB=$root/aux
SLEBIN=$root/aux
HYMANLIB=$root/src/hyman/hymanlib
export SLELIB SLEBIN PATH HYMANLIB

opts=$1
CC=$2
bsd=$3
F="$4"
POPT=$5

BOPT=
if [ $bsd -eq 1 ]; then
	BOPT=-b
fi
FOPT=
if [ "$F" != "" ]; then
	FOPT="-F \"$F\""
fi
	

#echo "buildprod $opts $BOPT $FOPT $POPT -C $CC" 1>&2
#buildprod -l $root/aux/complist $opts $BOPT $FOPT $POPT -C $CC 

 
if [ "$F" = "" ]; then
        echo "buildprod -l $root/aux/complist $opts $BOPT $POPT -C $CC" 1>&2
        buildprod -l $root/aux/complist $opts $BOPT $POPT -C "$CC"
else
        echo "buildprod -l $root/aux/complist $opts $BOPT -F \"$F\" $POPT -C $CC" 1>&2
        buildprod -l $root/aux/complist $opts $BOPT -F "$F" $POPT -C "$CC"
fi

