#ident	"@(#)cls4:demo/task/alph.V	1.1"
###############################################################################
#
# C++ source for the C++ Language System, Release 3.0.  This product
# is a new release of the original cfront developed in the computer
# science research center of AT&T Bell Laboratories.
#
# Copyright (c) 1991 AT&T and UNIX System Laboratories, Inc.
# Copyright (c) 1984, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of AT&T and UNIX System
#	
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
###############################################################################
Alphonse: 4
Gaston: 4
Alphonse: 3
Gaston: 3
Alphonse: 2
Gaston: 2
Alphonse: 1
Gaston: 1
Alphonse: 0
Gaston: 0
