#ident	"@(#)cls4:demo/task/shared.V	1.1"
###############################################################################
#
# C++ source for the C++ Language System, Release 3.0.  This product
# is a new release of the original cfront developed in the computer
# science research center of AT&T Bell Laboratories.
#
# Copyright (c) 1991 AT&T and UNIX System Laboratories, Inc.
# Copyright (c) 1984, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of AT&T and UNIX System
#	
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
###############################################################################
main
new pc(a)
new pc(b)
b: here we go
main()'s loop
main task
task a
task b
main task
task a
task b
main task
task a
task b
main task
task a
task b
main task
main task: done.
task a
task a: done.
task b
task b: done.
