#ident	"@(#)cls4:demo/task/sigtest.V	1.1"
###############################################################################
#
# C++ source for the C++ Language System, Release 3.0.  This product
# is a new release of the original cfront developed in the computer
# science research center of AT&T Bell Laboratories.
#
# Copyright (c) 1991 AT&T and UNIX System Laboratories, Inc.
# Copyright (c) 1984, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of AT&T and UNIX System
#	
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
###############################################################################
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
main:  all done.
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_sender sigusr1 sender:  about to send signal 16.
Sig_handler::interrupt()  got signal 16
Sig_task sigusr1 task, woke up for signal 16.
Sig_task sigusr1 task:  all done.
Sig_sender sigusr1 sender:  all done.
